# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c7084397477f55c7db464f7dd86a240a1ac00d8337f058176fb83f83c08cf5c28040b29680c523d5e7554c0b58c0abfb9cd607bb993195b905fd71cb563e933

test:
  secret_key_base: e2ef65b77a1c2be32f0e32984866db175b1ed34544f5723b3def5ff78313b0c14c8cf7330eb2ec226b4355f42ee2f1a4eadabc2c85e5bf4e2933e7d401f24f69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
